### ISSUE TITLE
axi_stream_dma_1 and _2 are missing in release v4.3.0

### ISSUE THREAD

**Issue by zixu** [slaclab/atlas-rd53-fmc-dev#3]
There is only axi_stream_dma_0 with v4.3.0 firmware for AtlasRd53FmcXilinxZcu102. 

The axi_stream_dma_1 is needed.  see https://github.com/slaclab/atlas-rd53-fmc-dev/blob/master_zixu/software/python/FmcDev.py#L274 

there are axi_stream_dma_0, _1, and _2  in the previous release.

**Comment by ruck314** [comment]
ZCU102 was not using latest SW driver. Reverted SURF as a work around until they upgrade the SW driver
