### ISSUE TITLE
FW issue for KC705 RJ45 

### ISSUE THREAD

**Issue by zixu** [slaclab/atlas-rd53-fmc-dev#4]
Hello, Larry,  @ruck314 

Testing the FW for KC705 RJ45. 
https://github.com/slaclab/atlas-rd53-fmc-dev/tree/master/firmware/targets/AtlasRd53FmcXilinxKc705_RJ45_1GbE

ethtool shows the link is connected, but ping failed. Using the default 192.168.2.10 for KC705, and use 192.168.2.11 for PC. 

The KCU105 RJ45-1G  and SFP-10G eth FW works without any issue.

**Comment by ruck314** [comment]
https://jira.slac.stanford.edu/browse/ATLASDAQ-59
